# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev
version: "3"

vars:
  # Frequently changed
  SERVICES: mysql nginx

  # Rarely changed

tasks:
  ####################
  #      Deploy      #
  ####################
  deploy:
    desc: Deploy the latest configuration
    deps:
      - checkout
    cmds:
      - ./assets/distribute_config.sh
      - task: restart-all
      - task: reload-sysctl

  ####################
  #     Utility      #
  ####################
  checkout:
    desc: Checkout and sync with the latest remote branch
    vars:
      BRANCH: '{{.CLI_ARGS | default "main"}}'
    cmds:
      - git fetch --all
      - git reset --hard origin/{{.BRANCH}}
      - git switch -C {{.BRANCH}} origin/{{.BRANCH}}

  enable:
    desc: Enable and start specified services
    cmds:
      - for: { var: CLI_ARGS }
        cmd: sudo systemctl enable --now {{.ITEM}}

  disable:
    desc: Disable and stop specified services
    cmds:
      - for: { var: CLI_ARGS }
        cmd: sudo systemctl disable --now {{.ITEM}}

  restart:
    desc: Restart specified services
    silent: true
    cmds:
      - for: { var: CLI_ARGS }
        cmd: sudo systemctl restart {{.ITEM}} && echo "{{.ITEM}} restarted"

  restart-all:
    desc: Restart all services related to the application
    cmds:
      - for: { var: SERVICES }
        cmd: sudo systemctl restart {{.ITEM}} && echo "{{.ITEM}} restarted"

  reload-sysctl:
    desc: Reload sysctl configuration
    cmds:
      - sudo sysctl -p

  ####################
  #     Internal     #
  ####################
