# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev
version: "3"

vars:
  # Frequently changed

  # Rarely changed
  CMD_INSTALL_DIR: /usr/local/bin

tasks:
  install-pprotein:
    internal: true
    vars:
      PPROTEIN_VERSION: "1.2.3"
      ALP_VERSION: "1.0.21"
      SLP_VERSION: "0.2.1"
      PPROTEIN_DOWNLOAD_URL: https://github.com/kaz/pprotein/releases/download/v{{.PPROTEIN_VERSION}}/pprotein_{{.PPROTEIN_VERSION}}_linux_amd64.tar.gz
      ALP_DOWNLOAD_URL: https://github.com/tkuchiki/alp/releases/download/v{{.ALP_VERSION}}/alp_linux_amd64.tar.gz
      SLP_DOWNLOAD_URL: https://github.com/tkuchiki/slp/releases/download/v{{.SLP_VERSION}}/slp_linux_amd64.tar.gz
    dir: /tmp/install-pprotein
    cmds:
      - curl -sL {{.PPROTEIN_DOWNLOAD_URL}} | tar xz
      - curl -sL {{.ALP_DOWNLOAD_URL}} | tar xz
      - curl -sL {{.SLP_DOWNLOAD_URL}} | tar xz
      - chmod +x pprotein pprotein-agent alp slp
      - sudo mv pprotein pprotein-agent alp slp {{.CMD_INSTALL_DIR}}
    status:
      - test -f {{.CMD_INSTALL_DIR}}/pprotein
      - test -f {{.CMD_INSTALL_DIR}}/pprotein-agent
      - test -f {{.CMD_INSTALL_DIR}}/alp
      - test -f {{.CMD_INSTALL_DIR}}/slp

  install-bottom:
    internal: true
    vars:
      BOTTOM_VERSION: "0.9.6"
      BOTTOM_DOWNLOAD_URL: https://github.com/ClementTsang/bottom/releases/download/{{.BOTTOM_VERSION}}/bottom_{{.BOTTOM_VERSION}}_amd64.deb
    dir: /tmp
    cmds:
      - curl -sLO {{.BOTTOM_DOWNLOAD_URL}}
      - sudo dpkg -i bottom_{{.BOTTOM_VERSION}}_amd64.deb
    status:
      - dpkg -l | grep bottom

  install-tools:
    desc: Install all tools
    cmds:
      - sudo apt-get update
      - sudo apt-get install -y tree jq graphviz
      - task: install-pprotein
      - task: install-bottom
